### ISSUE TITLE
[Wiki]: Create sequence diagram for bookmarking book pages

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#101]
### Issue Type

Deliverable

### Issue Description

I will create a sequence diagram showcasing how a user will bookmark a book page

**Comment by carmendetroit** [comment]
Thanks for your efforts! I guess here is the [Contribution](https://github.com/bounswe/bounswe2024group3/wiki/Sequence-Diagrams#21-bookmark-book-pages)
