### ISSUE TITLE
[Wiki]: Sequence Diagrams for User Authentication

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#120]
### Issue Type

Wiki

### Issue Description

I will create a sequence diagram showcasing how a user will login

**Comment by Abdusshh** [comment]
I will also create a sequence diagram showcasing how a user will register

**Comment by Abdusshh** [comment]
And also logout

**Comment by Abdusshh** [comment]
Here are the three sequence diagrams that i have created: https://github.com/bounswe/bounswe2024group3/wiki/Sequence-Diagrams#1-user-authentication-processes

**Comment by carmendetroit** [comment]
Thank you for your efforts! Looks done.
