### ISSUE TITLE
[Mobile]: Connect the endpoints

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#134]
### Issue Type

Feature Request

### Issue Description

We need to connect the back end endpoints to the mobile application that we are developing. 

We have 4 screen files and we need to implement login, register and book search with the corresponding screens.

**Comment by Abdusshh** [comment]
I did the necessary changes on this branch: https://github.com/bounswe/bounswe2024group3/tree/abdullah/mobile-endpoints

I also added the functionality of displaying the search results on the same branch.

I opened a pull request to merge it with main.

**Comment by carmendetroit** [comment]
Thanks for your efforts in Mobile team! Looks done!
