### ISSUE TITLE
[Mobile]: Skeleton Code for Mobile

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#140]
### Issue Type

Deliverable

### Issue Description

I developed the base structure for our React Native mobile app.

**Comment by carmendetroit** [comment]
The first version can be seen from this commit [Version 0.1](https://github.com/bounswe/bounswe2024group3/commit/84f8753ed2e2cfc31245b3a627c5abf1a97e4d09)

Dear reviewer please add yourself as a reviewer in Responsibility Assignment Matrix.

**Comment by Abdusshh** [comment]
Looks great! Thanks for your efforts.
