### ISSUE TITLE
[Web]: Create web release

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#146]
### Issue Type

Feature Request

### Issue Description

Relase the build of the frontend

**Comment by ekrembal** [comment]
Createsd a release: https://github.com/bounswe/bounswe2024group3/releases/tag/Group3-Web-Frontend-Release-v0.1

@onurdilsiz can you review

**Comment by onurdilsiz** [comment]
Thanks for your effort!

**Comment by ekrembal** [comment]
I edited the prev release, since we should release everyhing in one tag
Can be sen here: https://github.com/bounswe/bounswe2024group3/releases/tag/Group3-Practice-App-Release-v0.1
