### ISSUE TITLE
[Web]: Implement FeedCard and Feed page 

### ISSUE THREAD

**Issue by onurdilsiz** [bounswe/bounswe2024group3#153]
### Issue Type

Feature Request

### Issue Description

Implement FeedCard which includes post information and create the  Feed page

**Comment by onurdilsiz** [comment]
I implemented FeedCard which includes post information and create the Feed page

**Comment by onurdilsiz** [comment]
Can you review it @ekrembal?

**Comment by carmendetroit** [comment]
Thank you for your efforts.
