### ISSUE TITLE
[Mobile]: Create navbar

### ISSUE THREAD

**Issue by enesgules** [bounswe/bounswe2024group3#211]
### Issue Type

Feature Request

### Issue Description

We need to implement a navbar to move between the screens of the app. 

These screens are: Search, main and profile.

**Comment by Abdusshh** [comment]
I implemented these in this commit: https://github.com/bounswe/bounswe2024group3/commit/8723934cebd4222ba646c8f33aaec6ed4379e9e5

And here is the pull request: https://github.com/bounswe/bounswe2024group3/pull/208

**Comment by carmendetroit** [comment]
Thank you for your effort!
