### ISSUE TITLE
[Mobile]: Profile screen: Updating profile

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#212]
### Issue Type

Feature Request

### Issue Description

The user should be able to update his/her profile in the app. We need to implement this feature in the profile screen.

**Comment by Abdusshh** [comment]
Here is the commit for updating profile: https://github.com/bounswe/bounswe2024group3/commit/48baf3e15386d9f25b6b1a01a4d8c98dffbfad74

**Comment by carmendetroit** [comment]
Thank you for your effort!
