### ISSUE TITLE
[Mobile]: New colour palette and UX improvements 

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#214]
### Issue Type

Feature Request

### Issue Description

We want the app to look more beautiful and make it easier to use.

We are missing go back button in registration.

We want a colour palette that goes well with the concept of books. Creamy, woody colours should be fine.

**Comment by Abdusshh** [comment]
Here is the commit: https://github.com/bounswe/bounswe2024group3/commit/9226ffa313852f526d7dd15e863bd111c5521e01

Here is the final pull request for profile screen: https://github.com/bounswe/bounswe2024group3/pull/209

**Comment by carmendetroit** [comment]
Thank you for your effort!
