### ISSUE TITLE
[Mobile]: Implement initial feed page and creating posts

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#215]
### Issue Type

Feature Request

### Issue Description

We want the user to be able to create posts and see his/her and other people's posts in his/her feed.

**Comment by Abdusshh** [comment]
Here is the commit: https://github.com/bounswe/bounswe2024group3/commit/eca80188c4ea9e72785e926bf529179c15014000

I could not yet connect the endpoints for creating posts.

Here is the final pull request: https://github.com/bounswe/bounswe2024group3/pull/210

**Comment by carmendetroit** [comment]
Thank you for your effort!
