### ISSUE TITLE
[Wiki documentation]: Create personal page

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#240]
### Issue Type

Wiki

### Issue Description

We all have personal pages and our new member Jorge also needs one. Please create it using the template and add it to the home wiki page. 
Also please do not forget to add your weekly efforts every week.

### Additional Context

I will assign it to Jorge, when he is added to the repo

**Comment by jorgeveji112** [comment]
Personal page completed, now is ready to review

**Comment by Abdusshh** [comment]
LGTM!
