### ISSUE TITLE
[Wiki]: Functional Requirements: User Requirements

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#255]
### Issue Type

Wiki

### Issue Type

Deliverable

### Issue Description

- [x] Study Functional Requirements focusing on User Requirements. Format, characteristics, etc.
- [x] Document the findings.
- [ ] Implement the User Requirements for our project.

**Comment by burkaykinik** [comment]
Completed writing for the starter requirements. See user requirements section for [functional requirements](https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements)
