### ISSUE TITLE
[Wiki]: Nonfunctional Requirements

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#256]
### Issue Type

Wiki

### Issue Type

Deliverable

### Issue Description

- [x] Study Nonfunctional Requirements. Format, characteristics, etc.
- [x] Document the findings.
- [x] Implement the Nonfunctional Requirements for our project.

**Comment by ekrembal** [comment]
https://github.com/bounswe/bounswe2024group3/wiki/Nonfunctional-Requirements

We can use this @jorgeveji112 can you review?

**Comment by jorgeveji112** [comment]
I have checked them and I think we can use them, @ekrembal.

**Comment by ekrembal** [comment]
You can close the issue @jorgeveji112

**Comment by yspolatt** [comment]
I believe the requirements needed an update. Here I did [Revision](https://github.com/bounswe/bounswe2024group3/wiki/Nonfunctional-Requirements/_compare/3f2cd020662c1efc08f59b6203f48b84002a1354...f61e2d66c736aedf87f678b3c6c97bded5836868)

**Comment by ekrembal** [comment]
Thank you for your contribution @yspolatt
