### ISSUE TITLE
[Documentation]: Glossary

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#261]
### Issue Type

Wiki

### Issue Description

Define the terms used in requirements and other documents in glossary.

**Comment by yspolatt** [comment]
I wrote some basics but I believe it should be improved after the feedbacks we will get from instructors. Can you check if it is enough for now and close the issue? @onurdilsiz

**Comment by onurdilsiz** [comment]
I checked it, it is fine for now we can review them after requirements elicitation. Thanks for your efforts.
