### ISSUE TITLE
Create Personal Wiki Page

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#27]
### Issue Type

Wiki

### Issue Description

Update wiki page with your personal details

**Comment by uskudarli** [comment]
Should not close issue without giving reference or explanation to the work. Thus a link to the page in this case.

**Comment by ekrembal** [comment]
Here you can find the updated Personal Wiki Page,
[https://github.com/bounswe/bounswe2024group3/wiki/Ekrem-BAL](https://github.com/bounswe/bounswe2024group3/wiki/Ekrem-BAL)
