### ISSUE TITLE
[Mobile]: Create mobile development roadmap

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#272]
### Issue Type

Deliverable

### Issue Description

We need to meet and create a mobile development roadplan

**Comment by Abdusshh** [comment]
We will 
  - Set up the initial mobile project framework.
  - Create the navbar for mobile navigation.
  - Build the login page for user authentication on mobile devices.
  - Build the register page for new user sign-up on mobile devices.
  
  I will open the issues @Enestst

**Comment by Abdusshh** [comment]
I have created the issues you can track them from this issue here: #280

**Comment by Enestst** [comment]
I reviewed the issues, and they seem nice. Thank you!
Also, I added a new issue for the mobile team as we talked.
