### ISSUE TITLE
[Wiki]: Scenario Generation

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#274]
### Issue Type

Wiki

### Issue Description

Can you please create a descriptive scenario that pictures the post creation process in our system, step by step?

**Comment by Enestst** [comment]
@Abdusshh  can you review the scenario and check the requirements?

**Comment by Enestst** [comment]
https://github.com/bounswe/bounswe2024group3/wiki/Scenario-1-%E2%80%90-Content-Creation-for-a-Music
Here you can check the scenario.

**Comment by Abdusshh** [comment]
LGTM! Thank you!
