### ISSUE TITLE
[Mobile]: Set up the mobile project

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#276]
### Issue Type

Deliverable

### Issue Description

We need to set up the initial mobile project with correct configurations

**Comment by Enestst** [comment]
We have chosen React Native for our mobile project because it offers robust cross-platform capabilities and aligns with our team's existing expertise better than other available options.

**Comment by Enestst** [comment]
I initialized the mobile project with expo. Here is the pr https://github.com/bounswe/bounswe2024group3/pull/339

**Comment by eyusufatik** [comment]
closed by #339
