### ISSUE TITLE
[Wiki]: Create scenario for content filtering and interaction

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#284]
### Issue Type

Wiki

### Issue Description

We need to create a scenario showcasing our content filtering and interaction

**Comment by Abdusshh** [comment]
Here is the page: https://github.com/bounswe/bounswe2024group3/wiki/Scenario-5-%E2%80%90-Content-Filtering-and-Interaction
Can you review it @Enestst

**Comment by Enestst** [comment]
Reviewed it. Thanks, well done!
