### ISSUE TITLE
[Wiki]: Draw Class diagram

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#286]
### Issue Type

Wiki

### Issue Description

-

**Comment by burkaykinik** [comment]
Wrote the class diagrams with @yspolatt, but there are some parts that need to be updated after discussions with the group

**Comment by yspolatt** [comment]
Its done, I am closing the issue.

https://github.com/bounswe/bounswe2024group3/wiki/Class-Diagrams
