### ISSUE TITLE
[Project]: Decide on the name

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#288]
### Issue Type

General Question

### Issue Description

We should decide on the project name

**Comment by yspolatt** [comment]
As a group, we decided to name our project "SpotOn". The other options were MusicSpace, Spoti, Soundbox, Soundify, Songify, Micromusic, Spooty.

A play on "Spotify" and "Spot On", suggesting its the go-to place for Spotify discussions
