### ISSUE TITLE
[Wiki]: Draw Content Interaction Sequence Diagrams

### ISSUE THREAD

**Issue by onurdilsiz** [bounswe/bounswe2024group3#292]
### Issue Type

Wiki

### Issue Description

draw create a post, bookmark sequence diagrams

**Comment by Enestst** [comment]
I updated the create post sequence diagram with relative fields from the backend and added a bookmark functionality sequence diagram. Can you review it https://github.com/bounswe/bounswe2024group3/wiki/Sequence-Diagrams
@onurdilsiz @yspolatt

**Comment by onurdilsiz** [comment]
Looks good. Thanks for your efforts.
