### ISSUE TITLE
[Backend]: Add 127.0.0.1 to allowed hosts

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#323]
### Issue Type

Bug Report

### Issue Description

When a request is made from localhost, we get DisallowedHost error. Adding 127.0.0.1 to the ALLOWED_HOSTS solves this issue.

**Comment by burkaykinik** [comment]
Solved the issue and merged it to the main branch

**Comment by yspolatt** [comment]
It was solved and merged [Related PR](https://github.com/bounswe/bounswe2024group3/pull/324)
