### ISSUE TITLE
[Docker]: https://backend is not working

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#326]
### Issue Type

Bug Report

### Issue Description

In the docker-compose.yaml
it writes:
      REACT_APP_BACKEND_URL: http://backend:8000/api/

I think this should work, but in my case, using:
      REACT_APP_BACKEND_URL: http://127.0.0.1:8000/api/
worked

**Comment by eyusufatik** [comment]
closed by #352
