### ISSUE TITLE
[Milestone] Create pre-release

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#356]
### Issue Type

Deliverable

### Issue Description

The software must be dockerized and deployed.

Create a pre-release version of your software that marks this version:

	•	Release Name: 0.1.0-alpha (pre-release option)
	•	Release Description: Brief description of requirements that are covered
	•	Tag name: customer-milestone-1

Your release should include the Android package file (.apk).

All instructions for building and running the software should be provided, including the Docker build instructions and environment variables, if any. A fresh programmer who is fluent with various programming tools but not Docker itself nor your project should be able to do the deployment (for both web and mobile) by just following your steps.

**Comment by Abdusshh** [comment]
I have added the apk file.

**Comment by Abdusshh** [comment]
Here is the release: https://github.com/bounswe/bounswe2024group3/releases/tag/customer-milestone-1
