### ISSUE TITLE
[General Question]: Decide on the standards 

### ISSUE THREAD

**Issue by onurdilsiz** [bounswe/bounswe2024group3#368]
### Issue Type

General Question

### Issue Description

Discuss about the standards that can be beneficial for our project.

**Comment by Abdusshh** [comment]
We have discussed the following standards Web Annotation Data Model, Activity Streams 2.0, Jason LD and Web Content Accessibility Guidelines (WCAG) 2.2.

We have decided to utilize the Web Content Accessibility Guidelines (WCAG) 2.2 standard

**Comment by Abdusshh** [comment]
Here are couple of example standards that we are using:
1.2.1 Audio-only and Video-only (Prerecorded) 
For any audio-only or video-only content, provide a text alternative. This could be a summary or transcript of the discussion points, which would also enhance SEO.
2.4.2 Page Titled 
 Make sure each page has a unique, descriptive title that reflects the content, such as “Song Discussion – [Song Title].” This helps users navigate and improves accessibility.
1.4.1 Use of Color
Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.

**Comment by Enestst** [comment]
Well Done! This issue was completed 2 weeks ago.
