### ISSUE TITLE
[Research]: Learn Application Programming Interface Development

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#37]
### Issue Type

Wiki

### Issue Description

Research Application Programming Interface and write your findings on the wiki page. Make the findings available for the teammates.

**Comment by carmendetroit** [comment]
I started writing something about my research, it will be detailed.

https://github.com/bounswe/bounswe2024group3/wiki/API,-Use-and-Development

**Comment by carmendetroit** [comment]
@onurdilsiz @ekrembal Can you review this?

**Comment by ekrembal** [comment]
LGTM
