### ISSUE TITLE
[Documentation]: Revise Nonfunctional Requirements

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#370]
### Issue Type

Wiki

### Issue Description

Revise the nonfunctional requirements according to the standards we decided.

**Comment by onurdilsiz** [comment]
We have revised the nonfunctional requirements, and added this requirement to our requirements.
"2.3 The system should provide screen reading functionality for people with visual impairment who are willing to use our platform." 
Can you review @Enestst ?

**Comment by Enestst** [comment]
I reviewed the non-functional requirements. Well done!
