### ISSUE TITLE
[Documentation]: Accessibility Standards

### ISSUE THREAD

**Issue by yspolatt** [bounswe/bounswe2024group3#376]
### Issue Type

Wiki

### Issue Description

Document accessibility standards as asked:

Document the standard in your wiki as to:
what is it for, its benefits,
what are the requirements of following the standard,
how it will be enforced in practice.
Substantial commit(s) regarding the selected standard,
⁠Substantial commit(s) regarding domain specificity.

**Comment by yspolatt** [comment]
Can you review?  @Enestst

**Comment by Enestst** [comment]
I reviewed. You pointed out the standards very well which we decided. Thanks! We can add the link to the PR.
