### ISSUE TITLE
[Bug]: Fix the wiki sidebar 

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#38]
### Issue Type

Bug Report

### Issue Description

Lines in the wiki sidebar appear crooked. It needs to be fixed [here](https://github.com/bounswe/bounswe2024group3/wiki/_Sidebar/_edit)

**Comment by carmendetroit** [comment]
I tried to fix it, can be closed if you like my solution.

https://github.com/bounswe/bounswe2024group3/wiki/_Sidebar/_edit

**Comment by burkaykinik** [comment]
Looks nice, thanks!
