### ISSUE TITLE
[Research]: Learn Web Application Development

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#39]
### Issue Type

Wiki

### Issue Description

Research web application development and write your findings on the wiki page. Make the findings available for the teammates.

**Comment by Abdusshh** [comment]
Did my research and created this page and added it to the sidebar. Here is the page:https://github.com/bounswe/bounswe2024group3/wiki/Web-Application-Development

**Comment by Enestst** [comment]
Contacted @Abdusshh and added it to the API and Latest Technologies sections of the page.  https://github.com/bounswe/bounswe2024group3/wiki/Web-Application-Development
