### ISSUE TITLE
[Research]: Learn Mobile Application Development

### ISSUE THREAD

**Issue by onurdilsiz** [bounswe/bounswe2024group3#41]
### Issue Type

Wiki

### Issue Description

Research  aboout Mobile Application Development and write your findings on the wiki page. Make the findings available for the teammates.

**Comment by ekrembal** [comment]
We wrote our research here: https://github.com/bounswe/bounswe2024group3/wiki/Mobile-Application-Development

**Comment by ekrembal** [comment]
@eyusufatik can you review this

**Comment by eyusufatik** [comment]
looking good
