### ISSUE TITLE
[Mobile]: Tracking Issue

### ISSUE THREAD

**Issue by Enestst** [bounswe/bounswe2024group3#418]
### Issue Type

Deliverable

### Issue Description

- [x] #406 
- [x] #417  
- [x] #416
- [x] #415
- [x] #414
- [x] #413
- [x] #405
- [x] #459
- [x] #470 

### Additional Context

We are going to use this issue to track mobile development for Milestone 2.

**Comment by Abdusshh** [comment]
https://github.com/bounswe/bounswe2024group3/issues/470
This issue provides all the prs related to unit tests
