### ISSUE TITLE
[Wiki]: Functional Requirements: User Requirements (3 people)

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#45]
### Issue Type

Deliverable

### Issue Description

- [x] Study Functional Requirements focusing on User Requirements. Format, characteristics, etc.
- [x] Document the findings.
- [x] Implement the User Requirements for our project.

**Comment by ekrembal** [comment]
Thanks for helps @onurdilsiz @burkaykinik 
Added our docs to the wiki here: https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements
Currently dots are a little buggy, will fix them

**Comment by ekrembal** [comment]
Also we need to update the homepage and the right tab

**Comment by ekrembal** [comment]
Updated the homepage and sidebar, also updated the requirements with a better syntax.

**Comment by carmendetroit** [comment]
Thank you for your efforts!
