### ISSUE TITLE
[Deliverable][Urgent]: Picking a Domain

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#48]
### Issue Type

Deliverable

### Issue Description

We need to pick a domain for the project we will be working on. For further details, check [assignment description file](https://moodle.bogazici.edu.tr/pluginfile.php/1611546/mod_resource/content/1/Project%20Description%20and%20Requirements%20Eliciation.pdf). It would be helpful if every member comes with some ideas (examples in the description file.). 

- [ ] Plan the meeting.
- [ ] Pick the domain collaboratively.

**Comment by ekrembal** [comment]
Poll here: https://strawpoll.com/Q0ZpRABN9nM
