### ISSUE TITLE
[Deliverable]: Write primary features 

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#488]
### Issue Type

Deliverable

### Issue Description

We need to write primary features of our app for the checklist items

**Comment by Abdusshh** [comment]
We can check out our milestone tracking issues

**Comment by onurdilsiz** [comment]
- [ ] User Registration and Authentication 
- [ ] Profile Management
- [ ] User Interaction with other users
- [ ] Post Creation 
- [ ] Post Interaction
- [ ] Music Recommendations 
- [ ] Location based Music statistics 
- [ ] Music Playing
- [ ] Song Quiz
- [ ] Donation System for Artists
- [ ] Semantic Search 
- [ ] Filtering

**Comment by Abdusshh** [comment]
Features that are in progress:
- [ ] Profile Management
We currently display the information
- [ ] User Interaction with other users
We currently display the information related to the user but we haven't implemented functional follow or unfollow
- [ ] Song Quiz
This is a new idea we have came up with, we will suggest random songs for users to guess
- [ ] Donation System for Artists
Artists will have their crytpo account linked to their pages
- [ ] Filtering
We are planning to include filtering in the next milestone
