### ISSUE TITLE
[Branding]: Decide on the project name

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#49]
### Issue Type

General Question

### Issue Description

I love selecting a name for a project, lets decide on a good name.
ChatGPT Suggestions:
- LiteraLink - Combining "literature" or "literal" with "link," suggesting connections within the literary world.
- BookBridges - Highlighting the platform's role in bridging connections between readers, authors, and books.
- SemanticScribe - Emphasizing the semantic search aspect and the focus on written content.
- ReadRealm - Indicating a comprehensive domain or kingdom of reading material.
- LexiLoop - "Lexi" refers to words or literature, and "Loop" suggests a continuous, interactive cycle of engagement.
- NovelNet - Focusing on the novel aspect, but applicable to all kinds of books, and "Net" for the network of users and content.
- PagePals - Suggesting a friendly, community aspect around the pages of books.
- VerseVista - For a platform with a broad view (vista) of literary genres, including poetry (verse).
- InkInsight - Highlighting deep insights into books, with "Ink" representing the traditional medium of writing.
- TomeTracker - "Tome" for books, suggesting a tool for tracking and exploring literature.
- BiblioBond - Indicating a bond between users over bibliophilic interests.
- ScriptSphere - A global sphere for all things related to scripts and books.
- ChapterChase - Inviting users to chase after chapters, exploring and discovering content.
- NarrativeNexus - A nexus for narratives, connecting stories from various genres and authors.
- QuillQuest - Embarking on a quest for knowledge and stories, with "Quill" representing writing.

**Comment by carmendetroit** [comment]
We decided to name our project 'BiblioSearch'
