### ISSUE TITLE
[Type]: Review of the requirements

### ISSUE THREAD

**Issue by batuhansolmaz** [bounswe/bounswe2024group3#50]
### Issue Type

Wiki

### Issue Description

Detect the missing parts or wrong parts in the requirements while reviewing.

**Comment by abdarslan** [comment]
I reviewed the documentation and found complete.

**Comment by Abdusshh** [comment]
I reviewed the requirements and found complete. I only fixed minor spelling mistakes.

**Comment by Abdusshh** [comment]
Here is the page: https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements
