### ISSUE TITLE
[Planning]: Final presentation

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#509]
### Issue Type

Deliverable

### Issue Description

We should have a clear plan for the final presentation, including the user journey through the demo, the features we will show, and the outline of the presentation. We will try to have a scenario where we intertwine the web and mobile interfaces, not doing the same thing on both interfaces but showing how they complement each other.

**Comment by Enestst** [comment]
https://github.com/bounswe/bounswe2024group3/wiki/Lab-Report-10-12-2024

Here is the URL of the report.
