### ISSUE TITLE
[Wiki]: Renew the Home Page 

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#52]
### Issue Type

Wiki

### Issue Description

There are new pages created such as meeting notes, research pages, etc. We need to add these pages to the home page to access them easily.

**Comment by Abdusshh** [comment]
I have added the meeting notes to the home page here: https://github.com/bounswe/bounswe2024group3/wiki

**Comment by abdarslan** [comment]
I added the research pages to [home page.](https://github.com/bounswe/bounswe2024group3/wiki)
