### ISSUE TITLE
[Wiki]: Create a scenario

### ISSUE THREAD

**Issue by burkaykinik** [bounswe/bounswe2024group3#54]
### Issue Type

Deliverable

### Issue Description

I will create a scenario that will demonstrate how a user will bookmark a page and return to that page later.

**Comment by burkaykinik** [comment]
Created a scenario based on the description: https://github.com/bounswe/bounswe2024group3/wiki/Scenario-2-%E2%80%90-Creating-a-bookmark
@carmendetroit can you review please?

**Comment by carmendetroit** [comment]
Thank you for your effort
