### ISSUE TITLE
[Wiki]: Create a scenario

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#56]
### Issue Type

Deliverable

### Issue Description

I will create a scenario that will demonstrate how a user will search for a book for a specific genre that is above a certain rating.

**Comment by Abdusshh** [comment]
Created a scenario based on the description: https://github.com/bounswe/bounswe2024group3/wiki/Scenario-5-%E2%80%90-Filter-Genre-and-Rating
@carmendetroit can you review please?

**Comment by carmendetroit** [comment]
Thank you for your effort
