### ISSUE TITLE
[Wiki]: Split functional requirements

### ISSUE THREAD

**Issue by Abdusshh** [bounswe/bounswe2024group3#61]
### Issue Type

Wiki

### Issue Description

We need to split the functional requirements as user and system requirements. We currently have a mix of the two, I need to split them according to their category.

**Comment by Abdusshh** [comment]
Here is the new page: https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements

**Comment by onurdilsiz** [comment]
Thanks for your efforts
