### ISSUE TITLE
[Milestone Report]: Decisions and choices

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#64]
### Issue Type

Deliverable

### Issue Description

Write Decisions and choices you have made and your assessment regarding them. These include,
but are not limited to, conventions and choices related to issue management, meetings, and
wiki documentation)

**Comment by ekrembal** [comment]
@onurdilsiz can you review it?

**Comment by onurdilsiz** [comment]
Thanks for your effort!!!
