### ISSUE TITLE
[Planning]: Fix & Enhance the communication plan

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#81]
### Issue Type

Bug Report

### Issue Description

According to our controls, we have seen that our communication plan is not in the correct form. We need to fix it and put it in the correct form. Lecture slides gives this information about the format: 

![image](https://github.com/bounswe/bounswe2024group3/assets/65054425/5cb8e8cd-cba9-4190-82b1-ef75cae5c942)

**Comment by Abdusshh** [comment]
I categorised our meeting platforms and wrote descriptions for their use. I also organised them into a table for easier readability.

Here is the new communication plan: https://github.com/bounswe/bounswe2024group3/wiki/Communication-Plan

@carmendetroit can you look over my changes and close the issue if you are satisfied please.

**Comment by onurdilsiz** [comment]
Thanks for your efforts!
