### ISSUE TITLE
[Organization]: Decide on teams

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#85]
### Issue Type

General Question

### Issue Description

We should decide on who will work in what

**Comment by ekrembal** [comment]
Additional context:
Restrictions and recommendations
Back-end development

    API
        [Django REST framework](https://www.django-rest-framework.org/) (Python) and [Spring](https://spring.io/) (Java) are allowed for the API development.
    Database
        [MySQL](https://www.mysql.com/) is recommended for the database.
        [PostgreSQL](https://www.postgresql.org/) is allowed as an alternative to MySQL.


Front-end development

    Web design
        [React](https://react.dev/) is allowed for the web design, not frameworks based on React.
    Mobile design
        [React Native](https://reactnative.dev/) is allowed for the mobile design.

**Comment by Abdusshh** [comment]
We decided on the following teams:

Backend Team
1. Esad Yusuf Atik
2. Batuhan Solmaz
3. Burkay Kınık

Frontend Team
1. Ekrem Bal
2. Onur Dilsiz
3. Enes Sait Besler

Mobile Team
1. Abdullah Enes Güleş
2. Yusuf Suat Polat
3. Abdurrahman Arslan
