### ISSUE TITLE
[Wiki]: Draw Class diagrams

### ISSUE THREAD

**Issue by ekrembal** [bounswe/bounswe2024group3#87]
### Issue Type

Wiki

### Issue Description

Class diagrams for our database

**Comment by ekrembal** [comment]
I've designed a draft diagram: [here](https://github.com/bounswe/bounswe2024group3/wiki/Class-Diagrams)

**Comment by onurdilsiz** [comment]
Some progress have been made under on the [link](https://www.mermaidchart.com/app/projects/5f69a6db-1902-4844-89d8-7ef047b2f61d/diagrams/8f7e86ae-a3c9-424a-bb16-4b0adfe05f28/version/v0.1/edit)

**Comment by onurdilsiz** [comment]
I have expanded our class diagram [link](https://www.mermaidchart.com/app/projects/e5afb34c-146a-41e9-bc92-94365216792a/diagrams/eb9588a4-86ad-4a23-b5d1-8fa6fd7d998e/version/v0.1/edit)

**Comment by ekrembal** [comment]
@onurdilsiz looks like the link you've provided is broken

**Comment by onurdilsiz** [comment]
can you try this [link](https://www.mermaidchart.com/app/projects/e5afb34c-146a-41e9-bc92-94365216792a/diagrams/eb9588a4-86ad-4a23-b5d1-8fa6fd7d998e/version/v0.1/edit) ?

**Comment by onurdilsiz** [comment]
[link](https://www.mermaidchart.com/app/projects/e5afb34c-146a-41e9-bc92-94365216792a/diagrams/eb9588a4-86ad-4a23-b5d1-8fa6fd7d998e/version/v0.1/edit)

**Comment by Abdusshh** [comment]
Looks great! Thanks for your efforts!
