### ISSUE TITLE
[Wiki]: Draw Use Case Diagrams

### ISSUE THREAD

**Issue by abdarslan** [bounswe/bounswe2024group3#88]
### Issue Type

Wiki

### Issue Description

Draw diagrams using some tools for use cases.

**Comment by abdarslan** [comment]
I made some changes and redraw the diagram according to the feedbacks. It's ready for review. 
Relevant link is [here](https://github.com/bounswe/bounswe2024group3/wiki/Use-Case-Diagram).

**Comment by batuhansolmaz** [comment]
Reviewed it. It looks great.
