### ISSUE TITLE
[Doc Fix]: Glossary

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#89]
### Issue Type

Bug Report

### Issue Description

Please fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

*Glossary*

User/Registered User terms are used in requirements but not defined in the glossary.

Can users use your app without registration ? As I understood from your requirement 1.1 the term user refers to anyone who uses the platform, but the rest of your requirements need registration.

You should improve your glossary and define these terms for better clarity.

**Comment by abdarslan** [comment]
I edited the glossary and it is ready for review.

**Comment by carmendetroit** [comment]
Thank you for your effort!

[Changes](https://github.com/bounswe/bounswe2024group3/wiki/Glossary/_compare/04cfbbc34f22f00b6adbea5a2136c8a63fc6afae...d0a19217f56cd98a19e1e89112138c72535d688f)
