### ISSUE TITLE
[Doc Fix]: Requirements General

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#90]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

### General
  

It would be better if you numbered your requirement headings correctly. When I try to refer to the requirement 1.1, it is not clear whether it is a user requirement or a system requirement.

Writing a requirement like the one below creates ambiguity. Registration rules must be strict. Can a user register without giving his/her email address ? As I understood, he/she can. Please avoid using **"such as"** for these kinds of requirements.

> 1.1 Users can register for an account by providing necessary information, such as name, username, email, and password.

**Comment by carmendetroit** [comment]
I completed this task. You can see what has been changed from below.

[Functional Requirements](https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements/_compare/c04156fbd35fd07c748271a486b896193dd272b3...942486e8718571ac7009bcb9713b47027cbf4cae)

[Nonfunctional Requirements](https://github.com/bounswe/bounswe2024group3/wiki/Nonfunctional-Requirements/_compare/6d842cdb90d8e9f8133ca127d0d43deb4a9ff285...942486e8718571ac7009bcb9713b47027cbf4cae)

**Comment by Abdusshh** [comment]
Looks great! Thanks for your efforts.
