### ISSUE TITLE
[Doc Fix]: Fixing Requirement Format

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#92]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

> Ex: 1.1 The system shall **securely** store user registration information and authenticate users during login.

It is too broad, not clear.

> 2.2 The system shall manage user following/following relationships and updates.

> 3.5 The system shall have a feature for users to create and share their reading lists, fostering a community of book recommendations and discussions.

It is not clear. You need to define which activities. You should refrain from defining how but should specify which.

> 2.4 Users can follow/unfollow other users to receive updates on their activities.

**Comment by batuhansolmaz** [comment]
I changed 2.4 as follows : Users shall have the capability to follow and unfollow other users. This function will enable them to receive automatic updates and notifications regarding the book-related activities of users they follow. These activities include new posts, updated reading lists, book reviews, and ratings.
 
  I changed 2.2 as follows :  The system shall maintain a database of user relationships, tracking who follows whom and there shall be retrieval of followers and following queries in the database.
  
    I changed 3.5 as follows : The system shall enable users to compile and share reading lists which will be visible to other users, enhancing community engagement around shared book interests.
