### ISSUE TITLE
[Doc Fix]: Miscellaneous Errors

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#94]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

## Bookmark

It would be better to divide some actions in some requirements into different requirements.

Ex. 3.4 Users can view posts, bookmarks, and likes made by themselves and other users.

## Duplicates

There are some duplicates in requirements. Please detect and solve them.

> Ex1: 3.2 The system shall provide functionalities for bookmarking, liking/disliking posts, and rating books.
> 
> Ex2: 2.2 The system shall manage user following/following relationships and updates.

## Not-Complete

Users should be able to see notifications. More importantly, users *can*

> 2.4 Users can follow/unfollow other users to receive updates on their activities.

**Comment by ekrembal** [comment]
I think 3.2 and 2.2 are not duplicates since one mentions following users, and the other mentions liking content

**Comment by ekrembal** [comment]
Splitted 3.4 can be seen [here](https://github.com/bounswe/bounswe2024group3/wiki/Functional-Requirements/a89ec80eaa3fd1f38c546f887c5a14a5bfac6962).

**Comment by eyusufatik** [comment]
LGTM
