### ISSUE TITLE
[Doc Fix]: Nonfunctional Requirements

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#95]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were addressed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

## Non-Functional

You mentioned that you left some parts for future constraints but you should have determined them.

I believe you need to revise your non-functional requirements completely. May be you want to remove/rewrite some.

**Comment by onurdilsiz** [comment]
I added a compatibility part, I have decided the constraints as followed.

> 1. Performance Requirements
> 1.1 The system should handle a minimum of **1000** queries per second to accommodate peak usage times.
> 1.2 Response time for fetching data from the Wikidata API and posting new data to the Wikidata API should not exceed **2** seconds.
> 1.3 The system should support **1000** number of concurrent users without significant performance loss. 
> 

added this req to security
` 3.4 Data transmissions within the system shall exclusively utilize the HTTPS protocol to ensure secure communication.`
added this to reliability& availability
`5.3 The application should be available in Englis`h
This part is completely new
```
7. Compatibility
7.1 The system should be compatible with commonly used web browsers, namely Chrome, Firefox, Safari, and Edge.
7.2 The mobile application should be compatible with Android.
```
@Enestst Can you review and fix problems that you can detect?

**Comment by Enestst** [comment]
Reviewed, thanks for the effort.
