### ISSUE TITLE
[Doc Fix]: Scenarios

### ISSUE THREAD

**Issue by carmendetroit** [bounswe/bounswe2024group3#96]
### Issue Type

Bug Report

### Issue Description

Please detect and fix the problems below that were pointed by the feedbacks and clearly document what you changed. You are highly encouraged to take a look at the feedbacks on discord and take all the other considerations while you are solving your issue.

## Scenarios

You should have divide your scenarios into smaller steps to show user actions and support each step with your mockup.

Scenario 3 , no such requirement. I couldn't see a requirement for reply.

> 3.5.1 Users should be able to reply to comments, facilitating a discussion.

**Comment by eyusufatik** [comment]
I've completed udpating scenarios.

Can someone review?

**Comment by ekrembal** [comment]
Thanks @eyusufatik
